export type ServiceCategory = 'lawn' | 'yard' | 'snow' | 'home' | 'other';
export const services = [
 {slug:'lawn-care',category:'lawn',number:'01',title:'Lawn care',short:'Mow, trim, edge and leave things tidy.',description:'One-time or recurring care for residential lawns. Standard yards up to and including one-third acre start at $50. Larger yards are reviewed before a price is given.',tasks:['Mowing','Trimming and edging','Blow-off of hard surfaces']},
 {slug:'yard-outdoor',category:'yard',number:'02',title:'Yard & outdoor help',short:'A hand with the jobs outside.',description:'Mulch spreading, basic planting, small bush trimming, leaves and garden-bed cleanup, and reasonable ground-level material moving. We review the amount of work, access and materials before quoting.',tasks:['Mulch and basic planting','Small bush trimming','Seasonal cleanup']},
 {slug:'snow-clearing',category:'snow',number:'03',title:'Snow clearing',short:'Residential driveways, walks and accessible entries.',description:'Residential clearing with a hand shovel or walk-behind snow blower. We price snow work separately after reviewing the areas and conditions. No plowing, commercial lots, snow hauling, salt or deicer.',tasks:['Driveways','Sidewalks and walks','Accessible entries']},
 {slug:'home-help',category:'home',number:'04',title:'Help around the home',short:'Practical help with the small things.',description:'Furniture and household assembly, shelving and organization, household product setup, manageable moving, lightweight hanging within our height limit and minor drywall patches within capability. Several small things can go on one list.',tasks:['Assembly and setup','Organization','Several-small-things lists']},
] as const;
export const exclusions='We do not take on roofs, gutters, work above five feet, second-story or tree work, wiring, HVAC repair, structural work, major remodeling, chemical lawn applications, commercial snow, plowing, snow hauling, salt or deicer. Smart locks, hardwired lights and plumbing are not launch services while requirements are reviewed.';
export function findService(slug:string){return services.find(s=>s.slug===slug)}
