'use client';
import type {BusinessSnapshot} from '../lib/business-snapshot';
import {businessBrief} from '../lib/business-assistant';
import Icon from './crm-icons';
export default function BusinessBrief({data,error,onNavigate,onRetry}:{data:BusinessSnapshot|null;error:string;onNavigate:(section:string)=>void;onRetry:()=>void}){
 const tasks=data?businessBrief(data):[],first=tasks[0];
 const action=(task:typeof first)=><div className="brief-action" key={task.id}><h3>{task.title}</h3><p>{task.detail}</p><button className={task===first?'':'secondary'} onClick={()=>onNavigate(task.section)}>{task.label}<Icon name="arrow"/></button></div>;
 return <section className="card business-brief"><p className="eyebrow">Business assistant</p><h2>Your next move</h2>{!data?error?<><p role="alert">Business check unavailable. Saved records have not been changed.</p><button onClick={onRetry}>Retry business check<Icon name="refresh"/></button></>:<p role="status">Checking requests, visits, jobs and payments…</p>:<>{first?action(first):<p>No pending work was reported by this check. Review the day route before setting out.</p>}{tasks.length>1&&<details><summary>{tasks.length-1} more {tasks.length===2?'item':'items'} to consider</summary>{tasks.slice(1).map(action)}</details>}<p className="brief-checked">Checked {new Date(data.checkedAt).toLocaleTimeString('en-US',{timeZone:data.timezone,hour:'numeric',minute:'2-digit'})}. Based on saved records.</p><details className="assistant-connections"><summary>Connections &amp; automation</summary><dl>{[['gmail','Customer email'],['google_calendar','Google Calendar'],['maps','Maps provider'],['ai','AI provider']].map(([provider,label])=><div key={provider}><dt>{label}</dt><dd>{data.connections?.find(c=>c.provider===provider)?.status||'No verified connection'}</dd></div>)}</dl><p>Automatic email sending: {data.email.enabled&&data.email.automaticSending?'enabled':'not enabled in this check'}. Recorded connection status is separate from successful delivery; check Activity for outcomes.</p><p>Scheduling uses calendar and capacity checks. Confirmed customer times are changed through the scheduling workflow. Marketing drafts require your review.</p><button className="secondary" onClick={()=>onNavigate('Activity')}>Open activity &amp; messages<Icon name="arrow"/></button></details></> }</section>;
}
