'use client';
import {useEffect,useRef,useState} from 'react';
import type {CompanySettings} from '../../../packages/contracts';
import {validateConfiguration,releaseGates} from '../../../packages/domain/configuration';
import {sessionFetch} from '../lib/session-fetch';
const categories=[
 ['Lawn care','Mow, trim, blow and leaf management.','No herbicides; yard size and access require review.'],
 ['Yard & garden','Pull weeds, trim small bushes, plant small bushes and flowers; pick up, deliver and apply bulk or bagged mulch.','No herbicides. Customer prepays supplier for mulch and larger items. Hourly labor starts at supplier pickup; one minimum for combined work.'],
 ['Help around the home','Small home jobs reviewed individually before a quote.','No ladders or work above five feet. Regulated work requires separate compliance review.'],
 ['Snow clearing','Shovel or snow-blow residential driveways and sidewalks.','No salt; no road or parking-lot plowing.'],
 ['Concrete pressure washing','Residential driveway, walkway and patio concrete washing.','Customer supplies accessible outdoor water. Surface, drainage and runoff require review.'],
 ['Something else','Review the requested work and feasibility before offering service.','No automatic rate or scope commitment. Farmer contract labor: call to discuss work and rate.'],
] as const;
function template(name:string):CompanySettings{return {schemaVersion:1,displayName:name,timezone:'America/Chicago',currency:'USD',region:'IL',policyVersion:'ynsg-2026-10-02',privacyVersion:'ynsg-2026-10-02',cities:['DeKalb','Sycamore','Cortland'],brand:{navy:'#10283c',forest:'#315842',gold:'#edbd6b',cream:'#f8f6ef'},sender:'edhemmer@gmail.com',notificationRecipient:'edhemmer@gmail.com',intakeEnabled:false,hourly:{standardCents:6000,communityCents:4500,minimumMinutes:120,incrementMinutes:30,partialExtension:null},scheduling:{weekdays:[1,2,3,4,5],earliestStart:480,latestStart:900,endOfDay:1020,bufferMinutes:30,selectionMinutes:10,proposalMinutes:120,leadMinutes:1440,horizonMinutes:2160,pendingLimit:1},sellerLegalName:'',sellerVerified:false,invoiceTerms:null,taxTreatmentVerified:false,laborTaxTreatment:'unreviewed',review:{enabled:false,url:null}};}
export default function CompanySettingsPanel({organization,name}:{organization:string;name:string}){
 const [draft,setDraft]=useState<CompanySettings|null>(null),[version,setVersion]=useState(0),[approved,setApproved]=useState<string[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[pending,setPending]=useState(false),[preview,setPreview]=useState(false),[ready,setReady]=useState(false);
 const retry=useRef<{fingerprint:string;key:string}|null>(null);
 useEffect(()=>{let live=true;setDraft(null);setPreview(false);setError('');void sessionFetch('/api/configuration?organization='+encodeURIComponent(organization)).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load settings');if(live)setReady(d.ready===true);if(live&&d.configuration){setVersion(d.configuration.version);setDraft(d.configuration.settings);setApproved((d.catalog||[]).filter((c:{compliance:string})=>c.compliance==='approved').map((c:{name:string})=>c.name));}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[organization]);
 const change=(patch:Partial<CompanySettings>)=>{setDraft(d=>d?{...d,...patch}:d);setPreview(false);};
 const numeric=(label:string,key:keyof CompanySettings['scheduling'])=><label key={key}>{label}<input type="number" required min={0} value={String(draft?.scheduling[key]??'')} onChange={e=>change({scheduling:{...draft!.scheduling,[key]:Number(e.target.value)}})}/></label>;
 async function publish(){if(!draft)return;setPending(true);setError('');try{const settings=validateConfiguration(draft);const catalog=categories.map(([category,scope,exclusions])=>({name:category,scope,exclusions,compliance:approved.includes(category)?'approved':'review',pricingMode:category==='Something else'?'review':'hourly'}));const value={organizationId:organization,expectedVersion:version,settings,catalog};const fingerprint=JSON.stringify(value);if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,key:crypto.randomUUID()};const r=await sessionFetch('/api/configuration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...value,key:retry.current.key})});const d=await r.json();if(!r.ok)throw Error(d.error);setVersion(d.result.version);setPreview(false);setMessage('Settings version '+d.result.version+' published. Google and customer delivery remain separately controlled.');}catch(e){setError((e as Error).message);}finally{setPending(false);}}
 return <section className="card" aria-labelledby="settings-heading"><h2 id="settings-heading">Company settings</h2><p>Review business details and operating rules before publishing. These settings do not activate Google or customer emails.</p>{!ready&&<p className="note">Publishing awaits the approved database rollout. You can review the template here.</p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {!draft?<><p>No settings are published yet. The YNSG template is a starting point for your review.</p><button onClick={()=>{setDraft(template(name));setVersion(0);}}>Review YNSG settings template</button></>:<form onSubmit={e=>{e.preventDefault();try{validateConfiguration(draft);setError('');setPreview(true);}catch(e){setError((e as Error).message);}}}>
 <fieldset><legend>Business and email</legend><label>Business display name<input required value={draft.displayName} onChange={e=>change({displayName:e.target.value})}/></label><label>Legal seller name<input required minLength={2} value={draft.sellerLegalName} onChange={e=>change({sellerLegalName:e.target.value})}/></label><label>Timezone<input required value={draft.timezone} onChange={e=>change({timezone:e.target.value})}/></label><label>State or region<input required value={draft.region} onChange={e=>change({region:e.target.value})}/></label><label>Service cities, separated by commas<input required value={draft.cities.join(', ')} onChange={e=>change({cities:e.target.value.split(',').map(s=>s.trim())})}/></label><label>Gmail sender<input type="email" required value={draft.sender} onChange={e=>change({sender:e.target.value})}/></label><label>Owner notification email<input type="email" required value={draft.notificationRecipient} onChange={e=>change({notificationRecipient:e.target.value})}/></label></fieldset>
 <fieldset><legend>Rates and commercial review</legend><label>Standard hourly rate ($)<input required type="number" min="0.01" step="0.01" value={draft.hourly.standardCents/100} onChange={e=>change({hourly:{...draft.hourly,standardCents:Math.round(Number(e.target.value)*100)}})}/></label><label>Community hourly rate ($)<input required type="number" min="0.01" step="0.01" value={draft.hourly.communityCents/100} onChange={e=>change({hourly:{...draft.hourly,communityCents:Math.round(Number(e.target.value)*100)}})}/></label><p>One two-hour minimum per combined visit. Community eligibility is reviewed, never inferred.</p><label>Partial extension billing<select value={draft.hourly.partialExtension??''} onChange={e=>change({hourly:{...draft.hourly,partialExtension:e.target.value===''?null:e.target.value as 'ceil'|'exact'}})}><option value="">Not approved yet</option><option value="exact">Exact recorded minutes</option><option value="ceil">Round up to the next 30 minutes</option></select></label><label>Invoice terms<textarea value={draft.invoiceTerms??''} onChange={e=>change({invoiceTerms:e.target.value||null})}/></label><label><input type="checkbox" checked={draft.sellerVerified} onChange={e=>change({sellerVerified:e.target.checked})}/>I verified the legal seller identity.</label><label><input type="checkbox" checked={draft.taxTreatmentVerified} onChange={e=>change({taxTreatmentVerified:e.target.checked,laborTaxTreatment:e.target.checked?'reviewed_non_taxable':'unreviewed'})}/>I independently verified that this configured labor is non-taxable. Mixed or taxable charges remain blocked.</label></fieldset>
 <fieldset><legend>Scheduling policy — all values in minutes</legend><p>Weekdays: {draft.scheduling.weekdays.join(', ')} (Monday is 1). Normal two-hour visits; proposed times require owner approval.</p>{numeric('Earliest start after midnight', 'earliestStart')}{numeric('Latest start after midnight','latestStart')}{numeric('End of working day after midnight','endOfDay')}{numeric('Travel/setup buffer','bufferMinutes')}{numeric('Selection hold','selectionMinutes')}{numeric('Owner decision deadline','proposalMinutes')}{numeric('Minimum advance notice','leadMinutes')}{numeric('Booking horizon','horizonMinutes')}{numeric('Maximum pending alternatives per request','pendingLimit')}<p>The recorded YNSG policy is 24–36 hours ahead. It can offer no slots over closed days; review any change explicitly.</p></fieldset>
 <fieldset><legend>Colors</legend>{(['navy','forest','gold','cream'] as const).map(key=><label key={key}>{key}<input type="color" value={draft.brand[key]} onChange={e=>change({brand:{...draft.brand,[key]:e.target.value}})}/></label>)}</fieldset>
 <fieldset><legend>Catalog scope review</legend>{categories.map(([category,scope,exclusions])=><div key={category}><h3>{category}</h3><p>{scope}</p><p>{exclusions}</p><label><input type="checkbox" checked={approved.includes(category)} onChange={e=>{setApproved(a=>e.target.checked?[...a,category]:a.filter(s=>s!==category));setPreview(false);}}/>I reviewed this category for hourly quoting.</label></div>)}<label><input type="checkbox" checked={draft.intakeEnabled} onChange={e=>change({intakeEnabled:e.target.checked})}/>Enable database intake after the website connection is verified.</label></fieldset>
 <p>Remaining commercial checks: {releaseGates(draft).join('; ')||'No unchecked commercial gates in these settings.'}</p><button disabled={pending}>Preview settings</button>{preview&&<div className="card"><h3>Publish version {version+1}</h3><p>{draft.displayName} · {draft.timezone} · standard ${draft.hourly.standardCents/100}/hour · Community ${draft.hourly.communityCents/100}/hour</p><p>Database intake: {draft.intakeEnabled?'enabled':'disabled'}. Publishing retains historical invoice snapshots.</p><button type="button" disabled={pending||!ready} onClick={()=>void publish()}>Publish reviewed settings</button></div>}</form>}</section>;
}
