"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {sessionFetch} from '../lib/session-fetch';

type Expense={id:string;expense_date:string;vendor:string;category:string;description:string;amount_cents:number;payment_method:string;reference:string;business_expense_reversals:{reason:string;reversed_at:string}[]};
type Report={from:string;to:string;timezone:string;cashReceivedCents:number;expenseCents:number;cashAfterExpensesCents:number;issuedInvoicesCents:number;outstandingAsOfEndCents:number;expenseCount:number;paymentCount:number};
type Result={report:Report;expenses:Expense[];expenseRows:number;page:number;hasMore:boolean};
const usd=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
function cents(value:string){if(!/^\d{1,7}(\.\d{1,2})?$/.test(value))throw Error('Enter a positive dollar amount with up to two decimal places.');const [d,f='']=value.split('.');const amount=Number(d)*100+Number(f.padEnd(2,'0'));if(amount<1||amount>999999999)throw Error('Enter an amount greater than zero.');return amount}
function csvCell(value:string){return '"'+( /^[=+\-@\t\r]/.test(value)?"'":"")+value.replaceAll('"','""')+'"'}
export default function FinanceActivity({organization,companyName}:{organization:string;companyName:string}){
 const today=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const [from,setFrom]=useState(today.slice(0,4)+'-01-01'),[to,setTo]=useState(today),[page,setPage]=useState(0),[reload,setReload]=useState(0),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const key=useRef('');
 useEffect(()=>{setPage(0);setResult(null);key.current=''},[organization]);
 useEffect(()=>{let active=true;setResult(null);setError('');sessionFetch('/api/finance-activity?'+new URLSearchParams({organization,from,to,page:String(page)})).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load the report.');if(active)setResult(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[organization,from,to,page,reload]);
 async function command(payload:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{const r=await sessionFetch('/api/commands',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,organizationId:organization})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not save the expense.');key.current='';setMessage(payload.command==='RecordBusinessExpense'?'Expense recorded.':'Expense reversed.');setReload(x=>x+1);return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 async function record(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);let amount:number;try{amount=cents(String(f.get('amount')))}catch(err){setError((err as Error).message);return}if(!key.current)key.current=crypto.randomUUID();const ok=await command({command:'RecordBusinessExpense',key:key.current,date:f.get('date'),vendor:f.get('vendor'),category:f.get('category'),description:f.get('description'),cents:amount,method:f.get('method'),reference:f.get('reference'),confirmed:true});if(ok)form.reset()}
 async function reverse(row:Expense,e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const reason=String(new FormData(form).get('reason'));if(!key.current)key.current=crypto.randomUUID();const ok=await command({command:'ReverseBusinessExpense',key:key.current,id:row.id,reason});if(ok)form.reset()}
 function exportSummary(){if(!result)return;const r=result.report;const lines=[[companyName+' — cash activity summary'],['Company date range',r.from,r.to,r.timezone],['Metric','USD'],['Confirmed cash received',usd(r.cashReceivedCents)],['Recorded business expenses (after corrections)',usd(r.expenseCents)],['Cash received minus expenses',usd(r.cashAfterExpensesCents)],['Invoices issued in range',usd(r.issuedInvoicesCents)],['Outstanding on invoices issued through range end',usd(r.outstandingAsOfEndCents)],['Payment entries',String(r.paymentCount)],['Active expense entries',String(r.expenseCount)],['Note','Record summary only; excludes taxes, owner draws, unrecorded transactions and customer-paid materials.']];const csv='\uFEFF'+lines.map(row=>row.map(csvCell).join(',')).join('\r\n')+'\r\n';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`cash-activity-${r.from}-to-${r.to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="card" aria-label="Business cash activity"><h2>Business cash activity</h2><p>Recorded payments received and business expenses paid. Invoices issued are shown separately. This is a record summary, not a tax estimate.</p><div className="actions"><label>From <input type="date" value={from} onChange={e=>{setPage(0);setFrom(e.target.value)}} /></label><label>Through <input type="date" value={to} onChange={e=>{setPage(0);setTo(e.target.value)}} /></label><button type="button" onClick={()=>setReload(n=>n+1)}>Refresh report</button></div>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!result&&!error&&<p role="status">Loading the recorded totals…</p>}{result&&<><p>Business dates {result.report.from} through {result.report.to} ({result.report.timezone}).</p><dl className="finance-totals"><div><dt>Confirmed payments received</dt><dd>{usd(result.report.cashReceivedCents)}</dd></div><div><dt>Business expenses paid</dt><dd>{usd(result.report.expenseCents)}</dd></div><div><dt>Cash received minus expenses</dt><dd>{usd(result.report.cashAfterExpensesCents)}</dd></div><div><dt>Invoices issued during this range</dt><dd>{usd(result.report.issuedInvoicesCents)}</dd></div><div><dt>Outstanding on invoices issued through {result.report.to}</dt><dd>{usd(result.report.outstandingAsOfEndCents)}</dd></div></dl><p>{result.report.paymentCount} confirmed payment entries · {result.report.expenseCount} active expense entries. Corrections are excluded from expense totals and remain visible below.</p><button type="button" onClick={exportSummary}>Download summary CSV</button><p>This does not include owner draws, taxes, unrecorded transactions, or materials a customer paid directly to a supplier.</p></>}
 <details><summary>Record a paid business expense</summary><p>Only enter an expense you actually paid. Do not enter customer-paid materials or card or bank numbers.</p><form onSubmit={record}><label>Date paid <input name="date" type="date" max={today} required /></label><label>Vendor <input name="vendor" maxLength={160} required /></label><label>Category <select name="category">{['tools','fuel','supplies','vehicle','insurance','marketing','software','other'].map(s=><option value={s} key={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></label><label>What was purchased <input name="description" minLength={3} maxLength={500} required /></label><label>Amount paid (USD) <input name="amount" inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" required /></label><label>Payment method <select name="method"><option value="cash">Cash</option><option value="zelle">Zelle</option><option value="external_card">Card paid elsewhere</option><option value="external_transfer">Transfer paid elsewhere</option><option value="other">Other paid elsewhere</option></select></label><label>Receipt reference (no account numbers) <input name="reference" maxLength={160} required /></label><label className="check"><input type="checkbox" required />I confirmed this business expense was paid.</label><button disabled={busy}>Record expense</button></form></details>
 <h3>Expense entries</h3><p>{result?.expenseRows||0} entries in this range, including corrected entries. Most recent first.</p>{result?.expenses.map(row=><article className="finance-expense" key={row.id}><h4>{row.vendor} · {usd(row.amount_cents)}</h4><p>{row.expense_date} · {row.category} · {row.description}</p><p>{row.payment_method.replaceAll('_',' ')} · Receipt: {row.reference}</p>{row.business_expense_reversals.length?<p><strong>Reversed:</strong> {row.business_expense_reversals[0].reason}</p>:<details><summary>Correct this expense</summary><p>This creates a visible reversal. Record the corrected expense separately.</p><form onSubmit={e=>void reverse(row,e)}><label>Reason <input name="reason" minLength={5} maxLength={500} required /></label><button disabled={busy}>Reverse expense</button></form></details>}</article>)}{result&&<div className="actions"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous expenses</button><span>Page {page+1}</span><button disabled={!result.hasMore} onClick={()=>setPage(p=>p+1)}>Next expenses</button></div>}</section>
}
