"use client";
import {billingLabel} from "../lib/invoice-billing";
import type {InvoiceDocument} from "../lib/invoice-document";
const money=(c:number)=>(c/100).toLocaleString("en-US",{style:"currency",currency:"USD"});
export default function InvoiceView({invoice}:{invoice:InvoiceDocument}) {return <article className="branded-invoice">
 {invoice.sample&&<p role="note" className="note"><strong>SAMPLE — NOT A BILL.</strong> No work, payment or amount due has been recorded.</p>}
 <header className="invoice-brand"><img src="/brand/ynsg-logo.jpg" alt="Your Neighborhood Service Guy logo" width="180" height="120"/><div><p className="eyebrow">{invoice.businessName}</p>{invoice.businessEmail&&<p>{invoice.businessEmail}</p>}<h1>Invoice {invoice.number}</h1><p>Issued {new Date(invoice.issuedAt).toLocaleDateString('en-US',{timeZone:invoice.timezone})} ({invoice.timezone})</p></div></header>
 {invoice.dueDate&&<p>Recorded payment due date: <strong>{invoice.dueDate}</strong></p>}
 <section aria-labelledby="invoice-customer"><h2 id="invoice-customer">Customer and service address</h2>{invoice.recipient?<address style={{fontStyle:"normal",whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{invoice.recipient.name}<br/>{invoice.recipient.street}<br/>{[invoice.recipient.city,invoice.recipient.region,invoice.recipient.postalCode].filter(Boolean).join(", ")}<br/>{invoice.recipient.email}<br/>{invoice.recipient.phone}</address>:<p className="note">Customer details were not recorded on this older invoice. Contact the business if you need the missing details.</p>}</section>
 <table className="invoice-lines"><caption>Recorded work and approved charges</caption><thead><tr><th scope="col">Work</th><th scope="col">Charge</th></tr></thead><tbody>{invoice.lines.map((line,i)=><tr key={i}><td style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{line.description}<br/><small>{billingLabel(line)}{line.recordedMinutes!==undefined?` · ${line.recordedMinutes} actual minutes recorded`:""}</small></td><td>{line.chargedCents?money(line.chargedCents):'No charge'}</td></tr>)}</tbody></table>
 <section className="invoice-summary" aria-label="Invoice amounts"><p>Subtotal: {money(invoice.subtotalCents??invoice.totalCents)}</p>{invoice.taxComponents?.map((c,i)=><p key={i}>{c.label} ({c.ratePpm/10000}%): {money(c.taxCents)}</p>)}{!invoice.taxComponents?.length&&<p>Sales tax: {money(invoice.taxCents??0)}</p>}
 <p>Invoice total: <strong>{money(invoice.totalCents)}</strong></p><p>Confirmed payments: {money(invoice.paidCents)}</p><p>Remaining balance: <strong>{money(invoice.balanceCents)}</strong></p></section><section className="invoice-terms"><h2>Invoice terms</h2><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{invoice.terms}</p></section>
 </article>;}
