"use client";
import {useEffect,useRef,useState} from 'react';
import {sessionFetch} from '../lib/session-fetch';
type Delivery={enabled:boolean;recipient:string|null;status:string};
const labels:Record<string,string>={not_requested:'Not requested',pending:'Waiting for the email worker',leased:'Preparing email',sending:'Sending — awaiting provider result',accepted:'Accepted by Gmail. Inbox receipt is not confirmed.',failed:'Delivery failed; the worker may retry.',needs_reconciliation:'Delivery result is uncertain. Review before attempting another send.',dead_letter:'Delivery needs owner attention.',suppressed:'Delivery stopped.'};
export default function InvoiceDelivery({organization,invoice}:{organization:string;invoice:string}){
 const [data,setData]=useState<Delivery|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState(false);
 const retry=useRef<string|null>(null);
 async function load(){const r=await sessionFetch('/api/invoice-delivery?'+new URLSearchParams({organization,invoice}));const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{let active=true;setData(null);setError('');setReviewed(false);retry.current=null;sessionFetch('/api/invoice-delivery?'+new URLSearchParams({organization,invoice})).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false};},[organization,invoice]);
 async function send(){if(busy||!reviewed||!data?.enabled||!data.recipient||data.status!=='not_requested')return;setBusy(true);setError('');try{retry.current??=crypto.randomUUID();const r=await sessionFetch('/api/invoice-delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organization,invoice,reviewed:true,key:retry.current})});const d=await r.json();if(!r.ok)throw Error(d.error);setData(current=>current?{...current,status:d.delivery.status}:current);setReviewed(false);retry.current=null;}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section aria-label="Invoice email delivery"><h3>Invoice email</h3>{!data&&!error&&<p role="status">Checking delivery…</p>}{data&&<><p>Delivery: {labels[data.status]||'Review delivery status'}</p><p>Recipient: {data.recipient||'Not recorded on this invoice'}</p>{!data.enabled&&<p>Complete Google connection, sender receipt verification and email activation before sending.</p>}{data.status==='not_requested'&&<><p>Open the invoice above and review the customer, work and charges. This sends the invoice in the email; no PDF is attached.</p><label className="check"><input type="checkbox" checked={reviewed} disabled={busy||!data.enabled||!data.recipient} onChange={e=>setReviewed(e.target.checked)}/>I reviewed this issued invoice and recipient.</label><button disabled={busy||!reviewed||!data.enabled||!data.recipient} onClick={()=>void send()}>Send invoice email</button></>}<button disabled={busy} onClick={()=>{setError('');void load().catch(e=>setError(e.message))}}>Refresh delivery status</button></>}{error&&<p role="alert">{error}</p>}</section>;
}
