"use client";
import {billingLabel} from "../lib/invoice-billing";
import type {InvoiceDocument} from "../lib/invoice-document";
const money=(c:number)=>(c/100).toLocaleString("en-US",{style:"currency",currency:"USD"});
export default function InvoiceView({invoice}:{invoice:InvoiceDocument}) {
 const status=invoice.sample?"Sample invoice":invoice.balanceCents===0?(invoice.paidCents>0?"Paid":"No balance due"):invoice.paidCents>0?"Partially paid":"Payment due";
 return <article className="branded-invoice">
  {invoice.sample&&<p role="note" className="invoice-sample"><strong>SAMPLE — NOT A BILL.</strong> No work, payment or amount due has been recorded.</p>}
  <header className="invoice-brand"><img src="/brand/ynsg-logo.jpg" alt="Your Neighborhood Service Guy logo" width="210" height="140"/><div className="invoice-identity"><p className="invoice-kicker">Service invoice</p><h1>Invoice <span>#{invoice.number}</span></h1><span className="invoice-status">{status}</span></div></header>
  <div className="invoice-details"><section aria-labelledby="invoice-customer"><p className="invoice-kicker" id="invoice-customer">Billed to · Service address</p>{invoice.recipient?<address><strong>{invoice.recipient.name}</strong><span>{invoice.recipient.street}</span><span>{[invoice.recipient.city,invoice.recipient.region,invoice.recipient.postalCode].filter(Boolean).join(", ")}</span><span>{invoice.recipient.email}</span><span>{invoice.recipient.phone}</span></address>:<p className="note">Customer details were not recorded on this older invoice. Contact the business if you need the missing details.</p>}</section><section aria-label="Invoice details"><dl className="invoice-metadata"><div><dt>Issued</dt><dd>{new Date(invoice.issuedAt).toLocaleDateString('en-US',{timeZone:invoice.timezone,month:'long',day:'numeric',year:'numeric'})}</dd></div>{invoice.dueDate&&<div><dt>Due date</dt><dd>{invoice.dueDate}</dd></div>}<div><dt>From</dt><dd>{invoice.businessName}</dd></div>{invoice.businessEmail&&<div><dt>Contact</dt><dd>{invoice.businessEmail}</dd></div>}</dl></section></div>
  <table className="invoice-lines"><caption>Services &amp; charges</caption><thead><tr><th scope="col">Description</th><th scope="col">Amount</th></tr></thead><tbody>{invoice.lines.map((line,i)=><tr key={i}><td><strong>{line.description}</strong><small>{billingLabel(line)}{line.recordedMinutes!==undefined?` · ${line.recordedMinutes} actual minutes recorded`:""}</small></td><td>{line.chargedCents?money(line.chargedCents):'No charge'}</td></tr>)}</tbody></table>
  <div className="invoice-closing"><section className="invoice-terms"><p className="invoice-kicker">Payment terms</p><p>{invoice.terms}</p></section><section className="invoice-summary" aria-label="Invoice amounts"><dl><div><dt>Subtotal</dt><dd>{money(invoice.subtotalCents??invoice.totalCents)}</dd></div>{invoice.taxComponents?.map((c,i)=><div key={i}><dt>{c.label} ({c.ratePpm/10000}%)</dt><dd>{money(c.taxCents)}</dd></div>)}{!invoice.taxComponents?.length&&<div><dt>Sales tax</dt><dd>{money(invoice.taxCents??0)}</dd></div>}<div className="invoice-total"><dt>Invoice total</dt><dd>{money(invoice.totalCents)}</dd></div><div><dt>Confirmed payments</dt><dd>{money(invoice.paidCents)}</dd></div></dl><div className="invoice-balance"><span>{invoice.sample?'Sample balance':'Remaining balance'}</span><strong>{money(invoice.balanceCents)}</strong>{invoice.sample&&<small>No payment is due for this sample.</small>}</div></section></div>
 </article>;
}
