'use client';
import {useEffect,useId,useState,useRef} from 'react';
import {localDate,shiftLocalDate} from '../lib/day-plan';
import {z} from 'zod';
import {companySettings,type CompanySettings} from '../../../packages/contracts/index';
import {marketingDraft,type MarketingService} from '../lib/business-assistant';
import {sessionFetch} from '../lib/session-fetch';
import {publicError} from '../lib/public-errors';

const catalogSchema=z.array(z.object({name:z.string().min(2).max(80),scope:z.string().min(10).max(4000),exclusions:z.string().min(10).max(4000),compliance:z.enum(['approved','review','held']),pricing_mode:z.enum(['hourly','starting','quote','review'])})).max(100);
export default function MarketingDrafts({organization}:{organization:string}){
 const [open,setOpen]=useState(false);
 return <section className="card marketing-assistant"><p className="eyebrow">Marketing assistant</p><h2>Plan your next post</h2><p>Create a draft, edit it, then save a posting reminder in Google Calendar.</p><button className="secondary" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?'Close drafts':'Prepare a draft'}</button>{open&&<DraftEditor key={organization} organization={organization}/>}</section>;
}
function DraftEditor({organization}:{organization:string}){
 const attempt=useRef<{fingerprint:string;key:string}|null>(null);
 const [postingDate,setPostingDate]=useState(''),[saving,setSaving]=useState(false),[calendarUrl,setCalendarUrl]=useState<string|null>(null);
 const id=useId(),[settings,setSettings]=useState<CompanySettings|null>(null),[services,setServices]=useState<MarketingService[]>([]),[selected,setSelected]=useState(''),[format,setFormat]=useState<'post'|'flyer'>('post'),[draft,setDraft]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let live=true;const controller=new AbortController();setSettings(null);setServices([]);setDraft('');setError('');setNotice('');
  async function read(){try{const r=await sessionFetch('/api/configuration?'+new URLSearchParams({organization}),{cache:'no-store',signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error);if(!d.configuration)throw Error('Published company settings are unavailable.');const approved=companySettings.parse(d.configuration.settings),catalog=catalogSchema.parse(d.catalog).filter(s=>s.compliance!=='held');if(live){setSettings(approved);setPostingDate(shiftLocalDate(localDate(new Date(),approved.timezone),1));setServices(catalog);setSelected(catalog[0]?.name||'');}}catch(e){if(live&&!controller.signal.aborted)setError(publicError(e));}}
  void read();return()=>{live=false;controller.abort();};
 },[organization,retry]);
 async function planPost(){if(!settings||saving)return;const input={organization,title:selected,draft,date:postingDate},fingerprint=JSON.stringify(input);if(attempt.current?.fingerprint!==fingerprint)attempt.current={fingerprint,key:crypto.randomUUID()};setSaving(true);setNotice('');try{const r=await sessionFetch('/api/marketing-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,key:attempt.current.key})});const d=await r.json();if(!r.ok){setNotice(d.error||'Marketing plan could not be saved.');return;}setCalendarUrl(d.url);setNotice('Saved in Google Calendar with a 9 AM posting reminder. Your draft is in the event.');}catch{setNotice('The response was lost. Retry the same draft to check its saved status.');}finally{setSaving(false);}}
 function prepare(){try{const service=services.find(s=>s.name===selected);if(!settings||!service)return;setDraft(marketingDraft(settings,service,format));setNotice('Draft prepared. Review the scope, conditions and wording before posting.');setError('');}catch(e){setError(publicError(e));}}
 async function copy(){try{await navigator.clipboard.writeText(draft);setNotice('Copied. Nothing has been published or sent.');}catch{setNotice('Clipboard is unavailable. Select and copy the draft below.');}}
 return <div className="marketing-editor">{error?<><p className="error" role="alert">Published business details could not load. {error}</p><button className="secondary" onClick={()=>setRetry(n=>n+1)}>Retry</button></>:!settings?<p role="status">Loading published services and rates…</p>:!services.length?<p>No published services are available. Publish your service catalog to create a post.</p>:<><label htmlFor={id+'-service'}>Service<select id={id+'-service'} disabled={saving} value={selected} onChange={e=>{setSelected(e.target.value);setDraft('');setNotice('');setCalendarUrl(null);}}>{services.map(s=><option key={s.name} value={s.name}>{s.name}</option>)}</select></label><label htmlFor={id+'-format'}>Format<select id={id+'-format'} disabled={saving} value={format} onChange={e=>{setFormat(e.target.value as 'post'|'flyer');setDraft('');setNotice('');setCalendarUrl(null);}}><option value="post">Social post</option><option value="flyer">Flyer copy</option></select></label><button disabled={saving} onClick={prepare}>{draft?'Prepare again':'Prepare draft'}</button>{draft&&<><label htmlFor={id+'-copy'}>Edit your draft<textarea id={id+'-copy'} rows={12} maxLength={8000} disabled={saving} value={draft} onChange={e=>{setDraft(e.target.value);setNotice('');setCalendarUrl(null);}}/></label><button className="secondary" onClick={()=>void copy()}>Copy draft</button><label>Posting date<input type="date" required disabled={saving} value={postingDate} onChange={e=>{setPostingDate(e.target.value);setCalendarUrl(null);}}/></label><button disabled={saving||!postingDate||!draft.trim()} onClick={()=>void planPost()}>{saving?"Saving…":"Save posting reminder in Google Calendar"}</button>{calendarUrl&&<a className="button secondary" href={calendarUrl} target="_blank" rel="noopener noreferrer">Open saved marketing plan</a>}<p className="tiny">Review your draft before publishing. Calendar reminders do not publish posts or reserve appointment time.</p><a href="https://business.google.com/" target="_blank" rel="noopener noreferrer">Open Google Business Profile to publish</a></>}</>}{notice&&<p role="status">{notice}</p>}</div>;
}
