"use client";
import { publicError } from "../lib/public-errors";
import {useEffect,useState} from 'react';import {sessionFetch} from '../lib/session-fetch';import {notificationAttention,type AttentionRecord} from '../lib/notification-attention';
type Queue={records:AttentionRecord[];total:number;page:number;hasMore:boolean;enabled:boolean;checkedAt:string};
export default function NotificationAttention({organization}:{organization:string}){
 const [page,setPage]=useState(0),[refresh,setRefresh]=useState(0),[data,setData]=useState<Queue|null>(null),[error,setError]=useState('');
 useEffect(()=>{setPage(0)},[organization]);
 useEffect(()=>{let active=true;setData(null);setError('');sessionFetch('/api/notification-attention?'+new URLSearchParams({organization,page:String(page)})).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active)setData(d)}).catch(e=>{if(active)setError(publicError(e))});return()=>{active=false}},[organization,page,refresh]);
 return <section className="card" aria-label="Notification attention"><h2>Messages to check</h2>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Checking notifications…</p>}{data&&<>{!data.enabled&&<p>Email delivery is paused until Google connection, receipt verification and email activation are complete.</p>}<p>{data.total} due or unresolved messages. Oldest first.</p>{data.records.map(row=>{const info=notificationAttention(row,data.enabled,Date.parse(data.checkedAt));return <article className="notification-attention-row" key={row.id}><h3>{row.kind.replaceAll('.',' · ').replaceAll('_',' ')}</h3><strong>{info.label}</strong><p>{info.action}</p><p>Created {new Date(row.created_at).toLocaleString()} · Attempts: {row.attempts}</p>{row.kind.startsWith('invoice.')&&<a href={'/invoice?'+new URLSearchParams({organization,invoice:row.object_id})}>Open invoice</a>}{row.kind.startsWith('request.')&&<a href={'/?'+new URLSearchParams({organization,request:row.object_id})}>Open service request</a>}</article>})}{!data.records.length&&<p>No messages in this queue page. This does not confirm inbox receipt or that all automations are enabled.</p>}<div className="actions"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous messages</button><span>Page {page+1}</span><button disabled={!data.hasMore} onClick={()=>setPage(p=>p+1)}>Next messages</button></div></>}<button onClick={()=>setRefresh(n=>n+1)}>Refresh messages</button></section>;
}
