"use client";
import { publicError } from "../lib/public-errors";
import {useEffect,useState} from 'react';import {sessionFetch} from '../lib/session-fetch';import {notificationAttention,notificationName,type AttentionRecord} from '../lib/notification-attention';
type Queue={records:AttentionRecord[];total:number;page:number;hasMore:boolean;enabled:boolean;checkedAt:string};
export default function NotificationAttention({organization}:{organization:string}){
 const [page,setPage]=useState(0),[refresh,setRefresh]=useState(0),[data,setData]=useState<Queue|null>(null),[error,setError]=useState('');
 useEffect(()=>{setPage(0)},[organization]);
 useEffect(()=>{let active=true,inFlight=false;const controller=new AbortController();setData(null);setError('');
  async function read(){if(inFlight)return;inFlight=true;try{const r=await sessionFetch('/api/notification-attention?'+new URLSearchParams({organization,page:String(page)}),{cache:'no-store',signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error);if(active){setData(d);setError('');}}catch(e){if(active&&!controller.signal.aborted){setData(null);setError(publicError(e));}}finally{inFlight=false;}}
  void read();const timer=setInterval(()=>{if(document.visibilityState==='visible')void read();},30000);return()=>{active=false;controller.abort();clearInterval(timer);};
 },[organization,page,refresh]);
 return <section className="card" aria-label="Notification attention"><h2>Messages to check</h2>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Checking notifications…</p>}{data&&<>{!data.enabled&&<p>Email delivery is paused. Connect Gmail, confirm the test email arrived and enable notifications in Settings.</p>}<p>{data.total} due or unresolved messages. Oldest first.</p>{data.records.map(row=>{const info=notificationAttention(row,data.enabled,Date.parse(data.checkedAt));return <article className="notification-attention-row" key={row.id}><h3>{notificationName(row.kind)}</h3><strong>{info.label}</strong><p>{info.action}</p><p>Created {new Date(row.created_at).toLocaleString()} · Attempts: {row.attempts}</p>{row.kind.startsWith('invoice.')&&<a href={'/invoice?'+new URLSearchParams({organization,invoice:row.object_id})}>Open invoice</a>}{row.kind.startsWith('request.')&&<a href={'/?'+new URLSearchParams({organization,request:row.object_id})}>Open service request</a>}</article>})}{!data.records.length&&<p>No messages to check on this page. Delivery status does not confirm inbox receipt.</p>}<div className="actions"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous messages</button><span>Page {page+1}</span><button disabled={!data.hasMore} onClick={()=>setPage(p=>p+1)}>Next messages</button></div></>}<p className="tiny">Updates every 30 seconds while this screen is visible.</p><button onClick={()=>setRefresh(n=>n+1)}>Refresh messages</button></section>;
}
