'use client';
import {useEffect,useState,type FormEvent} from 'react';
type Membership={organization_id:string;role:string};
type RequestRecord={id:string;status:string;revision:number;created_at:string;original_submission:Record<string,string>};
type Quote={id:string;customer_id:string;current_version:number;status:string;quote_versions:{version:number;scope:string;labor_cents:number;duration_minutes:number}[]};
type Job={id:string;customer_id:string;quote_id:string;status:string;revision:number};
type Invoice={id:string;number:number;total_cents:number;issued_at:string;payments:{cents:number}[]};
type Data={company:{id:string;display_name:string;timezone:string;status:string};requests:RequestRecord[];customers:{id:string;display_name:string}[];quotes:Quote[];jobs:Job[];invoices:Invoice[];outbox:{id:string;kind:string;status:string;created_at:string}[]};
const usd=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100);
async function api(path:string,value?:unknown){const res=await fetch(path,{...(value?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}:{}),cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to complete this action.');return data;}
export default function Workspace({configured}:{configured:boolean}){
 const [session,setSession]=useState<{email:string;memberships:Membership[]}|null>(null),[checking,setChecking]=useState(configured),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[pending,setPending]=useState(false);
 const [org,setOrg]=useState(''),[data,setData]=useState<Data|null>(null),[section,setSection]=useState('Today');
 const [factor,setFactor]=useState<{factorId:string;enrolled:boolean;qr?:string;secret?:string}|null>(null),[mfaCode,setMfaCode]=useState('');
 async function loadSession(){try{const s=await api('/api/session');setSession(s);setOrg((o:string)=>o||s.memberships[0]?.organization_id||'');}catch{setSession(null);}finally{setChecking(false);}}
 useEffect(()=>{if(configured)void loadSession();},[configured]);
 async function refresh(selected=org){if(!selected)return;setError('');try{setData(await api(`/api/workspace?organization=${encodeURIComponent(selected)}`));}catch(e){setData(null);setError((e as Error).message);}}
 useEffect(()=>{setData(null);if(org)void refresh(org);},[org]);
 async function login(event:FormEvent){event.preventDefault();setPending(true);setError('');try{if(sent){await api('/api/session',{action:'verify',email,code});await loadSession();}else{const r=await api('/api/session',{action:'send',email});setSent(true);setMessage(r.message);}}catch(e){setError((e as Error).message);}finally{setPending(false);}}
 async function verifyMfa(event:FormEvent){event.preventDefault();setPending(true);setError('');try{await api('/api/mfa',{action:'verify',factorId:factor!.factorId,code:mfaCode});setFactor(null);setMfaCode('');await refresh();}catch(e){setError((e as Error).message);}finally{setPending(false);}}
 async function act(value:Record<string,unknown>){setPending(true);setError('');setMessage('');try{const r=await api('/api/commands',{organizationId:org,key:crypto.randomUUID(),...value});setMessage('Saved. The current record is shown below.');await refresh();return r;}catch(e){setError((e as Error).message);}finally{setPending(false);}}
 const role=session?.memberships.find(m=>m.organization_id===org)?.role;
 const operational=['owner','admin','dispatcher'].includes(role||'');const finance=['owner','admin','bookkeeper'].includes(role||'');
 const customerName=(id:string)=>data?.customers.find(c=>c.id===id)?.display_name||'Customer record';
 return <><header className="top"><div className="brand">{data?.company.display_name||'Service workspace'}<small>Requests, work and the next step.</small></div>{session&&<button className="secondary" onClick={async()=>{try{await api('/api/session',{action:'logout'});setSession(null);setData(null);setOrg('');setFactor(null);setEmail('');setCode('');setSent(false);}catch(e){setError((e as Error).message);}}}>Sign out</button>}</header><main className="shell" id="main">
 {!configured?<div className="auth card"><p className="eyebrow">Workspace setup</p><h1>A careful start.</h1><p>The CRM database connection is not configured for this deployment yet. Your public website remains available.</p><p className="note">This build is not ready for live customer operations.</p><a href="https://www.yourneighborhoodserviceguy.com/">Visit the public website</a></div>:checking?<p className="loading" role="status">Checking your session…</p>:!session?<form className="auth card" onSubmit={login}><p className="eyebrow">Welcome back</p><h1>One place for your work.</h1><p>Sign in with an email code. Staff also complete authenticator verification before opening business records.</p><label htmlFor="email">Email address</label><input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/>{sent&&<><label htmlFor="code">Email code</label><input id="code" inputMode="numeric" autoComplete="one-time-code" required value={code} onChange={e=>setCode(e.target.value)}/></>}<div className="actions"><button disabled={pending}>{pending?'Please wait…':sent?'Sign in':'Email me a code'}</button>{sent&&<button type="button" className="secondary" onClick={()=>{setSent(false);setCode('');}}>Request another code</button>}</div></form>:<>
 <p className="eyebrow">{session.email}</p>
 {!session.memberships.length?<div className="card"><h1>Your account is verified.</h1><p>No company or customer records have been shared with this account yet. An authorized owner must grant access. Matching an email address alone does not expose customer history.</p></div>:<><label htmlFor="company">Company</label><select id="company" value={org} onChange={e=>{setOrg(e.target.value);setFactor(null);setMessage('');}}>{session.memberships.map(m=><option key={m.organization_id} value={m.organization_id}>{data?.company.id===m.organization_id?data.company.display_name:m.organization_id} · {m.role}</option>)}</select>
 {!data&&<div className="card"><h2>Verify staff access</h2><p>Use your authenticator app to protect customer and financial records.</p><button disabled={pending} onClick={async()=>{setPending(true);setError('');try{setFactor(await api('/api/mfa',{action:'prepare'}));}catch(e){setError((e as Error).message);}finally{setPending(false);}}}>Set up or verify authenticator</button></div>}
 {factor&&<form className="card" onSubmit={verifyMfa}><h2>Authenticator verification</h2>{!factor.enrolled&&<><p>Scan this code in your authenticator app, then enter its six-digit code. Keep this setup key private.</p>{factor.qr&&<img className="qr" alt="Authenticator setup QR code" src={`data:image/svg+xml;base64,${btoa(factor.qr)}`}/>}<details><summary>Enter the key manually</summary><code>{factor.secret}</code></details></>}<label htmlFor="mfa">Six-digit code</label><input id="mfa" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" required value={mfaCode} onChange={e=>setMfaCode(e.target.value)}/><div className="actions"><button disabled={pending}>Verify</button></div></form>}
 {data&&<><nav className="nav" aria-label="Workspace">{['Today','Customers','Work','Money','More'].map(s=><button key={s} aria-current={section===s?'page':undefined} onClick={()=>setSection(s)}>{s}</button>)}</nav><div className="list-heading"><h1>{section==='Today'?'A clear next step.':section}</h1><button className="secondary" onClick={()=>void refresh()}>Refresh</button></div>
 {section==='Today'&&<><p className="muted">{new Intl.DateTimeFormat('en-US',{dateStyle:'full',timeZone:data.company.timezone}).format(new Date())}</p><div className="grid"><div className="card"><p className="eyebrow">Requests to review</p><div className="amount">{data.requests.filter(r=>['submitted','reviewing'].includes(r.status)).length}</div><p>Open each request, check scope and reply with the next step.</p><button onClick={()=>setSection('Work')}>Review requests</button></div><div className="card"><p className="eyebrow">Outstanding in this view</p><div className="amount">{usd(data.invoices.reduce((n,i)=>n+i.total_cents-i.payments.reduce((s,p)=>s+p.cents,0),0))}</div><p>Calculated from issued invoices and confirmed receipts shown here.</p><button onClick={()=>setSection('Money')}>View invoices</button></div></div><div className="card"><h2>Delivery needs attention</h2>{data.outbox.length?data.outbox.map(o=><div className="row" key={o.id}><strong>{o.kind.replaceAll('.',' · ')}</strong> <span className="badge">{o.status.replaceAll('_',' ')}</span></div>):<p>No queued communications are visible.</p>}<p className="note">Notification delivery remains inactive until the Gmail connection and worker are tested.</p></div></>}
 {section==='Customers'&&<div className="card"><h2>Customer relationships</h2>{data.customers.length?data.customers.map(c=><div className="row" key={c.id}><strong>{c.display_name}</strong><p className="tiny muted">{c.id}</p></div>):<p>No customer records yet. Reviewing and publishing a quote can create an explicitly linked customer record.</p>}<p className="muted">Showing up to 50 authorized records.</p></div>}
 {section==='Work'&&<><h2>Service requests</h2>{!data.requests.length&&<div className="card"><p>No requests in this workspace yet. Public requests continue through the existing website until the CRM intake switch is enabled.</p></div>}{data.requests.map(r=><article className="card" key={r.id}><span className="badge">{r.status}</span><h2>{r.original_submission.name}</h2><p><strong>{r.original_submission.service}</strong> · {r.original_submission.task}</p><p>{r.original_submission.description}</p><p>{r.original_submission.street}, {r.original_submission.city}</p><div className="actions"><a href={`tel:${r.original_submission.phone}`}>Call {r.original_submission.phone}</a><a href={`mailto:${r.original_submission.email}`}>Email customer</a></div>{operational&&r.status==='submitted'&&<div className="actions"><button disabled={pending} onClick={()=>void act({command:'ReviewRequest',id:r.id,revision:r.revision,status:'reviewing'})}>Start review</button></div>}{operational&&['reviewing','quoted'].includes(r.status)&&<QuoteForm request={r} pending={pending} submit={act}/>}</article>)}
 <h2>Quotes and approvals</h2>{data.quotes.length?data.quotes.map(q=>{const v=q.quote_versions.find(v=>v.version===q.current_version);return <article className="card" key={q.id}><span className="badge">{q.status} · Version {q.current_version}</span><h3>{customerName(q.customer_id)}</h3><p>{v?.scope}</p><p className="amount">{usd(v?.labor_cents||0)}</p><p>Approved hourly labor · {v?.duration_minutes} minutes. Separate costs require separate approval.</p>{['owner','admin'].includes(role||'')&&q.status==='sent'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({command:'ApproveQuote',id:q.id,version:q.current_version,evidence:f.get('evidence')});}}><label>Record the customer's actual approval<input name="evidence" minLength={10} maxLength={2000} required placeholder="Who approved, when and how"/></label><div className="actions"><button disabled={pending}>Record approval</button></div></form>}</article>}):<p>No quotes yet.</p>}
 <h2>Jobs</h2>{data.jobs.map(j=><article className="card" key={j.id}><span className="badge">{j.status.replaceAll('_',' ')}</span><h3>{customerName(j.customer_id)}</h3>{['working','paused'].includes(j.status)&&['owner','admin'].includes(role||'')?<button disabled={pending} onClick={()=>void act({command:'CompleteAndInvoice',id:j.id,revision:j.revision})}>Complete &amp; Invoice</button>:<p>Scheduling and field actions are being integrated. This record has not been marked as completed.</p>}</article>)}</>}
 {section==='Money'&&<><p>Issued amounts remain fixed. Payment status comes from confirmed receipts.</p>{!data.invoices.length&&<div className="card"><h2>No issued invoices</h2><p>Complete approved work to create an invoice after seller identity, payment terms and tax treatment are configured.</p></div>}{data.invoices.map(i=>{const balance=i.total_cents-i.payments.reduce((n,p)=>n+p.cents,0);return <article className="card" key={i.id}><span className="badge">{balance===0?'Paid':balance<i.total_cents?'Partially paid':'Unpaid'}</span><h2>Invoice {i.number}</h2><p className="amount">{usd(balance)} outstanding</p><p>Issued total {usd(i.total_cents)}</p>{finance&&balance>0&&<PaymentForm invoice={i} pending={pending} submit={act}/>}</article>})}</>}
 {section==='More'&&<div className="card"><h2>Company readiness</h2><p className="badge">{data.company.status}</p><p>Timezone: {data.company.timezone}</p><p>This staged build has database request, quote, invoice and confirmed-payment commands. It has not passed the full operating release gates.</p><ul><li>Verify seller identity, compliance, tax treatment and invoice terms.</li><li>Set travel buffer, holidays and territory.</li><li>Connect and test Gmail, auth email and Google Calendar.</li><li>Verify backup restoration, native devices and operator usability.</li></ul><p>No review destination has been activated. No customer emails are sent by this screen.</p></div>}</>}
 </>}
 </>}
 {error&&<p role="alert" className="error card">{error}</p>}{message&&<p role="status" className="note">{message}</p>}
 </main></>;
}
function QuoteForm({request,pending,submit}:{request:RequestRecord;pending:boolean;submit:(v:Record<string,unknown>)=>Promise<unknown>}){return <details><summary>Prepare an hourly quote</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit({command:'PublishQuote',id:request.id,revision:request.revision,scope:f.get('scope'),minutes:Number(f.get('minutes')),community:f.get('community')==='on',eligibilityReviewed:f.get('reviewed')==='on',customerId:null});}}><label>Exact scope<textarea name="scope" required minLength={10} maxLength={5000} defaultValue={request.original_submission.description}/></label><label>Approved duration<select name="minutes"><option value="120">2 hours</option><option value="150">2½ hours</option><option value="180">3 hours</option><option value="210">3½ hours</option><option value="240">4 hours</option></select></label><label className="check"><input type="checkbox" name="community"/>Community Rate</label><label className="check"><input type="checkbox" name="reviewed"/>Customer eligibility reviewed</label><p>Publishing creates a new immutable quote version. It does not send an email or schedule the job.</p><button disabled={pending}>Publish quote version</button></form></details>}
function PaymentForm({invoice,pending,submit}:{invoice:Invoice;pending:boolean;submit:(v:Record<string,unknown>)=>Promise<unknown>}){const [key]=useState(()=>crypto.randomUUID());return <details><summary>Record a received payment</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),amount=String(f.get('amount'));if(!/^\d+(\.\d{1,2})?$/.test(amount))return;const [whole,fraction='']=amount.split('.');const cents=Number(whole)*100+Number(fraction.padEnd(2,'0'));void submit({command:'RecordPayment',key,id:invoice.id,cents,method:f.get('method'),reference:f.get('reference'),receivedAt:new Date(String(f.get('receivedAt'))).toISOString(),confirmed:true});}}><label>Amount received (USD)<input name="amount" inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" required/></label><label>Method<select name="method"><option value="cash">Cash</option><option value="zelle">Zelle</option></select></label><label>Received at<input name="receivedAt" type="datetime-local" required/></label><label>Receipt reference<input name="reference" maxLength={300} required/></label><label className="check"><input type="checkbox" required/>I confirmed the money was received.</label><button disabled={pending}>Record confirmed payment</button></form></details>}
