import {test} from 'node:test';import assert from 'node:assert/strict';
import {requestInput,companySettings} from '../packages/contracts/index';
import {validateConfiguration} from '../packages/domain/configuration';
const config={schemaVersion:1,displayName:'Synthetic',sellerLegalName:'Synthetic Seller',timezone:'America/Chicago',currency:'USD',region:'IL',policyVersion:'test',privacyVersion:'test',cities:['DeKalb'],brand:{navy:'#10283c',forest:'#315842',gold:'#edbd6b',cream:'#f8f6ef'},sender:'owner@example.invalid',notificationRecipient:'owner@example.invalid',intakeEnabled:false,hourly:{standardCents:6000,communityCents:4500,minimumMinutes:120,incrementMinutes:30,partialExtension:null},scheduling:{weekdays:[1,2,3,4,5],earliestStart:480,latestStart:900,endOfDay:1020,bufferMinutes:30,selectionMinutes:10,proposalMinutes:120,leadMinutes:1440,horizonMinutes:2160,pendingLimit:1},sellerVerified:false,invoiceTerms:null,taxTreatmentVerified:false,laborTaxTreatment:'unreviewed',review:{enabled:false,url:null}};
test('one published configuration carries required commercial fields and exact minute horizon',()=>{const parsed=validateConfiguration(config);assert.equal(parsed.scheduling.horizonMinutes,2160);assert.equal(companySettings.safeParse({...config,scheduling:{...config.scheduling,horizonMinutes:1440}}).success,false);assert.equal(companySettings.safeParse({...config,scheduling:{...config.scheduling,horizonDays:2}}).success,false);});
test('configuration rejects inaccessible colors and a last start that cannot fit the minimum',()=>{assert.throws(()=>validateConfiguration({...config,brand:{...config.brand,navy:config.brand.cream}}));assert.throws(()=>validateConfiguration({...config,scheduling:{...config.scheduling,endOfDay:1000}}));assert.equal(companySettings.safeParse({...config,entitlements:{finance:true}}).success,false);});
const request={name:'Synthetic',phone:'5550000000',email:'test@example.invalid',street:'100 Test Street',city:'DeKalb',communityRate:'No',services:[{service:'Lawn care',task:'Leaf management'},{service:'Yard & garden',task:'Mulch pickup, delivery and spreading'}]};
test('cross-category request retains all items without requiring generic notes',()=>{assert.equal(requestInput.parse(request).services?.length,2);assert.equal(requestInput.safeParse({...request,services:[request.services[0],request.services[0]]}).success,false);assert.equal(requestInput.safeParse({...request,services:[]}).success,false);});
test('Other keeps its explicit description requirement and a bounded selection count',()=>{assert.equal(requestInput.safeParse({...request,services:[{service:'Something else',task:''}]}).success,false);assert.equal(requestInput.safeParse({...request,services:[{service:'Something else',task:''}],description:'Please review this specific job.'}).success,true);assert.equal(requestInput.safeParse({...request,services:Array(16).fill(request.services[0])}).success,false);});
