import {billingLabel} from "./invoice-billing.ts";
import {emailLayout,emailSignedText,type EmailIdentity} from '../../../lib/email-layout.js';
import type {InvoiceDocument} from './invoice-document.js';
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(c:number)=>(c/100).toLocaleString('en-US',{style:'currency',currency:'USD'});
export function invoiceMessage(d:InvoiceDocument,identity?:EmailIdentity){
 if(!d.recipient)throw Error('INVOICE_CUSTOMER_DETAILS_REQUIRED');
 const customer=d.recipient;
 const address=[customer.street,customer.city,customer.region,customer.postalCode].filter(Boolean).join(', ');
 const issued=new Date(d.issuedAt).toLocaleDateString('en-US',{timeZone:d.timezone});
 const text=[d.businessName,`Invoice ${d.number}`,`Issued ${issued}`,...(d.dueDate?[`Recorded payment due date: ${d.dueDate}`]:[]),`Customer: ${customer.name}`,`Service address: ${address}`,`Email: ${customer.email}`,`Phone: ${customer.phone}`,...d.lines.map(l=>`${l.description}${l.billingBasis?` (${billingLabel(l)})`:""}: ${l.chargedCents?money(l.chargedCents):'No charge'}`),`Subtotal: ${money(d.subtotalCents??d.totalCents)}`,...(d.taxComponents?.length?d.taxComponents.map(c=>`${c.label} (${c.ratePpm/10000}%): ${money(c.taxCents)}`):[`Sales tax: ${money(d.taxCents??0)}`]),`Invoice total: ${money(d.totalCents)}`,`Payments received: ${money(d.paidCents)}`,`Remaining balance: ${money(d.balanceCents)}`,'Invoice terms:',d.terms,'Reply to this email if you have a question.'].join('\n\n');
 const html=emailLayout(d.businessName, `Invoice ${d.number}`, `Your invoice from ${d.businessName}`, `<p>Issued ${escape(issued)}</p>${d.dueDate?`<p>Recorded payment due date: ${escape(d.dueDate)}</p>`:""}<div style="padding:18px;background:#f8f6ef;border:1px solid #d6dfd7;border-radius:12px"><h2 style="font-size:20px;margin:0 0 12px">Customer and service address</h2><p>${escape(customer.name)}<br>${escape(address)}<br>${escape(customer.email)}<br>${escape(customer.phone)}</p></div><table style="width:100%;border-collapse:collapse;table-layout:fixed"><caption style="text-align:left;font-weight:bold">Work and charges</caption><thead><tr><th scope="col" style="text-align:left">Work</th><th scope="col" style="text-align:right;width:34%">Charge</th></tr></thead><tbody>${d.lines.map(l=>`<tr><td style="padding:12px 8px 12px 0;border-bottom:1px solid #d6dfd7;white-space:pre-wrap">${escape(l.description)}<br><small>${escape(billingLabel(l))}</small></td><td style="padding:12px 0;text-align:right;border-bottom:1px solid #d6dfd7">${l.chargedCents?money(l.chargedCents):'No charge'}</td></tr>`).join('')}</tbody></table><div style="margin:24px 0;padding:18px;background:#f8f6ef;border:1px solid #d6dfd7;border-radius:12px"><h2 style="font-size:20px;margin:0 0 12px">Invoice summary</h2><p>Subtotal: ${money(d.subtotalCents??d.totalCents)}</p>${d.taxComponents?.length?d.taxComponents.map(c=>`<p>${escape(c.label)} (${c.ratePpm/10000}%): ${money(c.taxCents)}</p>`).join(''):`<p>Sales tax: ${money(d.taxCents??0)}</p>`}<p>Invoice total: <strong>${money(d.totalCents)}</strong></p><p>Payments received: ${money(d.paidCents)}</p><p>Remaining balance: <strong>${money(d.balanceCents)}</strong></p></div><h2 style="font-size:20px">Invoice terms</h2><p style="white-space:pre-wrap">${escape(d.terms)}</p><p>Reply to this email if you have a question.</p>`,identity);
 return {to:customer.email,subject:`${d.businessName} — Invoice ${d.number}`,body:emailSignedText(text,identity),html};
}
