import { googleMessages } from "./google-messages";
// Only reviewed messages reach product screens. Provider text, exception messages,
// database details and unknown future codes always fall back to plain language.
const messages:Record<string,string>={
 UNAUTHORIZED:'Sign in to continue.',
 OWNER_ACCESS_REQUIRED:'Owner access is required.',
 STALE_REVISION:'This record changed. Refresh before continuing.',
 STALE_CONNECTION:'The connection changed. Refresh before trying again.',
 CAPACITY_CONFLICT:'That time is no longer available. Please choose another time.',
 GOOGLE_SETUP_REQUIRED:'Google setup needs attention before connecting.',
 RECONNECT_REQUIRED:'Google access expired or was revoked. Reconnect in Settings.',
};
const approved=new Set([
 ...Object.values(googleMessages),
 'Sign in to continue.','Owner access is required.','Please try again.',
 'The email provider has temporarily limited sign-in emails. Check your inbox for the newest message already sent and open its link in the browser where you requested it. If it has expired, wait before requesting another email.',
 'Email sign-in is unavailable. Check workspace email setup or try again later.',
 'Your saved sign-in has expired. Sign in once to continue.',
 'Your sign-in could not be renewed right now. Please try again; no new email is needed.',
 'Check your email and password, or use Forgot password.',
 'Account email could not be sent. Please try again later.',
 'That code is invalid or expired. Request a new code.',
 'This appointment link has expired or changed. Please contact the business for a new link.',
 'Please wait a minute before trying again.',
 'Your appointment or response changed. Refresh the details before continuing.',
 'This retry has different details. Refresh before continuing.',
 'Your request for another time is already awaiting review.',
 'This action is no longer available for the appointment.',
 'Open your appointment email link to continue.',
 'Check the appointment details and your message.',
 'We could not complete this action. Your appointment has not been canceled.',
 'This account is not connected to that company.',
 'This invoice is unavailable to your account.','Invoice unavailable.',
 'This job changed. Refresh before continuing.',
 'Settings changed. Reload before publishing.',
 'Settings were not published. Check your access and required fields.',
 'An appointment or its buffer overlaps this time. Move it before blocking this time.',
 'This block changed. Reload and try again.',
 'This time could not be blocked. Check your access and dates.',
 'Choose a valid calendar date.',
 'Your saved details are not available for a new request. Contact the business to check your account connection.',
 'Check your services and details before sending.',
 'Please wait before sending another request.',
 'Your request was not saved. Check your linked details or contact the business.',
 'Notes could not be saved or opened. Check your company access and try again.',
 'Note is too long.',
 'Check the work descriptions, whole minutes, charges and reasons for no charge. The draft was not saved.',
 'The Google event changed. Resolve its sync issue before approval.',
 'Complete the scheduling review and choose valid resources and times.',
 'Times could not be checked. No appointment was created.',
 'Connect an authorized Google calendar before checking times.',
 'Could not sign out. Try again.',
 'Use no more than two decimal places.',
 'The saved request could not be confirmed. Try again with the same details.',
]);
export function publicError(error:unknown,fallback='We could not complete that action. Please try again. If it keeps happening, contact the business.'):string {
 const value=typeof error==='string'?error:error instanceof Error?error.message:'';
 return googleMessages[value]||messages[value]|| (approved.has(value)?value:fallback);
}
