export const schedulingMessages:Record<string,string>={
 ROUTE_UNAVAILABLE:'Travel could not be verified. Check routing before scheduling.',
 ROUTE_TRAVEL_CONFLICT:'There is not enough driving time between these visits. Choose another appointment time.',
 ROUTE_ADDRESS_REQUIRED:'A customer address needs review before travel can be checked.',
 ROUTE_PICKUP_REVIEW:'A neighboring visit includes a supplier pickup. Review its location before scheduling.',
 ROUTE_DEPARTURE_PAST:'A previous visit has already ended. Review current travel before scheduling.',
 STALE_REVISION:'The request, calendar or settings changed. Refresh and review again.',
 SERVICE_REVIEW_REQUIRED:'A selected service is on hold. Review its scope in Company settings before scheduling.',
 CAPACITY_CONFLICT:'There is not enough free time for the visit, travel and buffer.',
 GOOGLE_BUSY_CONFLICT:'Your Google calendar has conflicting busy time.',
 PROVIDER_FACTS_REQUIRED:'Current Google calendar checks are required.',
 FEASIBILITY_REVIEW_REQUIRED:'The review expired or changed. Refresh and review again.',
 DURATION_REVIEW_REQUIRED:'Review the quoted duration before scheduling. An accepted duration requires a change approval.',
 OUTSIDE_BOOKING_WINDOW:'Choose a date within your advance-notice and booking-window settings.',
 OUTSIDE_OPERATING_HOURS:'Choose a start and duration inside your operating hours.',
 OWNER_BLOCK:'This time overlaps an owner block.',
 RESOURCE_UNAVAILABLE:'A selected resource is unavailable.',
 REQUEST_UNAVAILABLE:'Review the service request first.',
 PENDING_LIMIT:'Resolve the existing proposed time before adding another.',
 REPLACEMENT_REQUIRED:'Keep the original and explicitly propose a replacement.',
 ORIGINAL_UNAVAILABLE:'The original appointment changed. Refresh before rescheduling.',
 IDEMPOTENCY_CONFLICT:'This retry has different details. Refresh before continuing.',
 TRANSITION:'This proposal expired or is no longer awaiting approval.',
};
