'use client';
import {useState} from 'react';
import Link from 'next/link';
const groups=[{id:'lawn-care',title:'Lawn Care',example:'Grass, edges, and seasonal care'},{id:'yard-outdoor',title:'Yard & Outdoor Help',example:'Mulch, hand weeding, concrete washing'},{id:'snow-clearing',title:'Snow Clearing',example:'Residential driveways and walks'},{id:'home-help',title:'Help Around the Home',example:'Assembly, organizing, cosmetic repairs'},{id:'something-else',title:'Something Else',example:'Tell us what you have in mind'}];
const contacts=[{id:'address',label:'Service address, city & ZIP',type:'text',auto:'street-address'},{id:'name',label:'Full name',type:'text',auto:'name'},{id:'phone',label:'Phone',type:'tel',auto:'tel'},{id:'email',label:'Email',type:'email',auto:'email'}];
export default function RequestForm({initialService}:{initialService?:string}){
 const initial=initialService==='pressure-washing'?'yard-outdoor':initialService;
 const [selected,setSelected]=useState<string[]>(groups.some(g=>g.id===initial)?[initial!]:[]);
 const [data,setData]=useState<Record<string,string>>(initialService==='pressure-washing'?{description:'Concrete pressure washing — '}:{});
 const [errors,setErrors]=useState<Record<string,string>>({});
 const [community,setCommunity]=useState(false);
 function update(id:string,value:string){setData(d=>({...d,[id]:value}));setErrors(e=>({...e,[id]:''}));}
 function validate(id:string){const value=(data[id]||'').trim();let error='';if(contacts.some(c=>c.id===id)&&!value)error='Please enter your '+(id==='address'?'service address, city and ZIP':contacts.find(c=>c.id===id)!.label.toLowerCase())+'.';else if(id==='email'&&value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))error='Enter an email address such as name@example.com.';else if(id==='phone'&&value&&value.replace(/\D/g,'').length<10)error='Enter a phone number with at least 10 digits.';else if(id==='description'&&selected.includes('something-else')&&!value)error='Tell us a little about the work you need.';setErrors(e=>({...e,[id]:error}));}
 return <form className="request-form single-request" onSubmit={e=>e.preventDefault()} noValidate>
 <div className="form-opening"><span className="eyebrow">YOUR REQUEST</span><p>A few details to get the conversation started.</p></div>
 <div className="notice" role="status"><strong>Online sending is being set up.</strong> Please <a href="tel:+17706302094">call 770-630-2094</a> or <a href="sms:+17706302094">text us</a> to make a request today. This form does not send or save your details yet.</div>
 <fieldset><legend>What do you need help with? <span className="required-note">Required · choose one or more</span></legend><div className="service-choices">{groups.map(g=><label className="service-tile" key={g.id}><input type="checkbox" id={'service-'+g.id} checked={selected.includes(g.id)} onChange={()=>setSelected(s=>s.includes(g.id)?s.filter(x=>x!==g.id):[...s,g.id])}/><span><strong>{g.title}</strong><small>{g.example}</small></span></label>)}</div></fieldset>
 <label className="field" htmlFor="description">{selected.includes('something-else')?'What do you need help with? *':'Tell us a little about the job (optional)'}<textarea id="description" rows={3} maxLength={3000} required={selected.includes('something-else')} value={data.description||''} onChange={e=>update('description',e.target.value)} onBlur={()=>validate('description')} aria-invalid={!!errors.description} aria-describedby={errors.description?'description-error':undefined}/>{errors.description&&<span className="field-error" id="description-error">{errors.description}</span>}</label>
 <div className="field-grid">{selected.includes('lawn-care')&&<label className="field" htmlFor="lawn-size">Lawn size, if you know (optional)<select id="lawn-size" value={data.lawnSize||''} onChange={e=>update('lawnSize',e.target.value)}><option value="">Not sure / discuss later</option><option>Up to and including one-third acre</option><option>Larger than one-third acre</option></select></label>}{selected.includes('snow-clearing')&&<label className="field" htmlFor="driveway-size">Driveway size (optional)<select id="driveway-size" value={data.drivewaySize||''} onChange={e=>update('drivewaySize',e.target.value)}><option value="">Not sure / discuss later</option><option>1-car</option><option>2-car</option><option>3-car or larger</option><option>Walks or entry only</option></select></label>}</div>
 <fieldset className="contact-fields"><legend>Where is the work, and how can we reach you?</legend><p className="fine">We serve DeKalb, Sycamore and Cortland, Illinois. Include the city and ZIP so we can check the location. Phone and email are both needed to follow up about your request.</p><div className="field-grid">{contacts.map(f=><label className="field" htmlFor={f.id} key={f.id}>{f.label} *<input id={f.id} type={f.type} autoComplete={f.auto} required maxLength={300} value={data[f.id]||''} onChange={e=>update(f.id,e.target.value)} onBlur={()=>validate(f.id)} aria-invalid={!!errors[f.id]} aria-describedby={errors[f.id]?f.id+'-error':undefined}/>{errors[f.id]&&<span className="field-error" id={f.id+'-error'}>{errors[f.id]}</span>}</label>)}</div></fieldset>
 <label className="field" htmlFor="preference">Is there a day or time that usually works? (optional)<input id="preference" maxLength={300} value={data.preference||''} onChange={e=>update('preference',e.target.value)}/><span>This is a preference, not a booking.</span></label>
 <div className="community-choice"><label className="check-row"><input type="checkbox" checked={community} onChange={e=>{setCommunity(e.target.checked);if(!e.target.checked)update('rate','')}}/>I’d like to ask about the Community Rate (optional)</label><p className="fine">For seniors age 70 or older, veterans, single moms, and people with disabilities. Approved hourly labor is $45/hour, with a two-hour minimum of $90. Lawn, snow, materials, parts and disposal are not automatically discounted.</p>{community&&<label className="field" htmlFor="rate">Private choice (optional)<select id="rate" value={data.rate||''} onChange={e=>update('rate',e.target.value)}><option value="">Discuss with us</option><option>Age 70 or older</option><option>Veteran</option><option>Single mom</option><option>Person with a disability</option></select><span>No proof, diagnosis, income or personal history needed.</span></label>}</div>
 <p className="submit-expectation">We’ll review your request and contact you about the work, price and a time. Sending this does not book a visit.</p><button className="button send-request" type="submit" disabled aria-describedby="sending-status">Send Request <span aria-hidden="true">↗</span></button><p className="fine" id="sending-status">Sending is unavailable while setup is completed. <a href="tel:+17706302094">Call Us — 770-630-2094</a>.</p>
 <p className="fine privacy-note">* Required. Please don’t include door codes, payment details or sensitive information. This draft clears when you leave or reload the page. <Link href="/privacy">Privacy information</Link>.</p>
 </form>
}
