export const services = [
 {id:'lawn-care',title:'Lawn care',tag:'Mowing, trimming, edging, and blow-off.',description:'Mowing, trimming, edging, and blow-off for residential yards. One-time help or recurring care.',items:['Mow, trim / edge, and blow-off','One-time or recurring care'],note:'Starting at $50 for standard residential yards up to and including ⅓ acre. Larger yards are reviewed individually.'},
 {id:'yard-outdoor',title:'Yard & outdoor help',tag:'Practical help with garden beds and outdoor tasks.',description:'Mulch spreading, hand weed pulling, basic planting, leaf cleanup, and small bush trimming.',items:['Mulch spreading and prepaid mulch pickup','Basic planting and garden-bed cleanup','Pulling weeds by hand — no herbicides','Leaf and seasonal cleanup','Small bush trimming and manageable yard materials'],note:'Safe, ground-level work only. No tree work or chemical lawn applications.'},
 {id:'home-help',title:'Help around the home',tag:'Assembly, organizing, and small cosmetic repairs.',description:'Assembly, organizing, manageable moving, and small cosmetic wall repairs—including scratches and minor surface damage.',items:['Furniture and household assembly','Shelving and organization','Moving manageable household items','Household product setup','Lightweight hanging within the height limit','Small cosmetic wall repairs','A list of several small things'],note:'Each task is reviewed. No structural work, regulated trades, or work above five feet.'},
 {id:'pressure-washing',title:'Concrete pressure washing',tag:'Concrete surface cleaning, reviewed individually.',description:'Tell us which concrete surface needs cleaning and what condition it is in.',items:['Concrete surface cleaning, reviewed individually'],note:'Scope, site conditions, and price are confirmed before any work is scheduled.'},
 {id:'snow-clearing',title:'Snow clearing',tag:'Residential driveways, walkways, and accessible entries.',description:'Residential driveways, sidewalks, walkways, and accessible entries, using a shovel or walk-behind snow blower.',items:['Residential driveways','Sidewalks and walkways','Accessible entries'],note:'Separately priced after review. No plowing, commercial snow, snow hauling, salt, ice melt, or deicer.'},
 {id:'something-else',title:'Something else?',tag:'Start with what you need.',description:'Not sure where your task fits? Describe it, and we’ll review whether we can help.',items:['Describe your task in your own words'],note:'A request is not acceptance of the work. Service boundaries still apply.'}
] as const;
export const phone = '770-630-2094';
