export const emailEscape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const emailParagraph = text => `<p style="margin:0 0 18px;white-space:pre-wrap;overflow-wrap:anywhere">${emailEscape(text)}</p>`;
export function emailButton(label, url, secondary=false) {
 const u=new URL(url);
 if(u.protocol!=='https:'||u.username||u.password)throw Error('INVALID_EMAIL_ACTION');
 return `<p style="margin:20px 0"><a class="${secondary?'mail-button-secondary':'mail-button'}" href="${emailEscape(u.toString())}" style="display:inline-block;padding:14px 22px;border:2px solid #315842;border-radius:8px;background:${secondary?'#ffffff':'#315842'};color:${secondary?'#315842':'#ffffff'};font-size:17px;font-weight:bold;line-height:1.4;text-decoration:underline">${emailEscape(label)}</a></p>`;
}
// Content is trusted template markup. Escape every dynamic value before composing it.
export function emailLayout(company, title, preview, content) {
 return `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><style>@media(prefers-color-scheme:dark){.mail-body{background:#121c25!important}.mail-card,.mail-content{background:#1c2c38!important;color:#f5f7f6!important}.mail-content h2,.mail-content h3,.mail-content p{color:#f5f7f6!important}.mail-content a{color:#b9e1cc!important}.mail-content .mail-button{color:#ffffff!important}.mail-content .mail-button-secondary{background:#1c2c38!important;color:#b9e1cc!important;border-color:#b9e1cc!important}}</style></head><body class="mail-body" style="margin:0;background:#f8f6ef;color:#10283c;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden;mso-hide:all">${emailEscape(preview)}</div><table role="presentation" width="100%" style="border-collapse:collapse"><tr><td style="padding:16px 12px"><table class="mail-card" role="presentation" width="100%" style="max-width:600px;margin:auto;border-collapse:collapse;background:#ffffff;border:1px solid #d6dfd7"><tr><td style="padding:24px;background:#10283c;color:#ffffff;border-bottom:5px solid #c6a35b"><p style="margin:0;font-size:16px;line-height:1.5;font-weight:bold;color:#ffffff">${emailEscape(company)}</p><h1 style="margin:12px 0 0;font-size:28px;line-height:1.25;color:#ffffff">${emailEscape(title)}</h1></td></tr><tr><td class="mail-content" style="padding:24px;background:#ffffff;color:#10283c;font-size:17px;line-height:1.6;overflow-wrap:anywhere">${content}</td></tr></table></td></tr></table></body></html>`;
}
