import Link from 'next/link';
import { ArrowRight, Check, Phone } from 'lucide-react';
import { RequestForm } from '@/components/request-form';
const services=[['Lawn & yard','Mowing, edging, garden-bed weeding, mulch, leaves, and other ground-level outdoor jobs.'],['Snow clearing','Residential drives, walks, and accessible entries. We review the areas and conditions first.'],['Help around the home','Assembly, organizing, manageable moving, and small cosmetic jobs within our limits.'],['Something else','Tell us what is on your list. We will let you know honestly if it is work we can take on.']];
export default function Home(){return <>
<section className="hero"><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">DEKALB · SYCAMORE · CORTLAND</p><div className="audience-pill"><span aria-hidden="true">🇺🇸</span> Community Rate for the neighbors we especially serve</div><h1>Got a few jobs on your list?</h1><p className="hero-answer">Let’s see if we can help.</p><p className="lead">We especially work for seniors, veterans, single moms, and people with disabilities. You may have things around the house or yard that do not call for a contractor. Tell us what needs doing, and we will talk through what we can do, what it will cost, and when we can come by.</p><div className="actions"><Link className="button button-primary" href="#request">Tell us what you need <ArrowRight size={18}/></Link><a className="button button-secondary" href="tel:+17706302094"><Phone size={18}/> Call 770-630-2094</a></div><p className="quiet">Serving DeKalb, Sycamore, and Cortland, Illinois.</p></div><div className="hero-card"><div className="hero-card-top"><span>HOME &amp; YARD HELP</span><span aria-hidden="true">✦</span></div><h2>What is on your list?</h2><p>One or two jobs, or a handful of small things that have been waiting.</p><div className="mini-list">{['Lawn and yard','Snow clearing','Help around the home','Something else'].map(item=><div key={item}><Check size={18}/><span>{item}</span></div>)}</div></div></div></section>
<section className="section" aria-labelledby="services-heading"><div className="container"><p className="eyebrow green">PRACTICAL HELP CLOSE TO HOME</p><h2 id="services-heading">A few ways we may be able to help.</h2><p className="section-intro">Choose the closest fit. If your job does not fit neatly in a box, choose Something else and describe it.</p><div className="service-grid">{services.map(([title,text],i)=><article className="service-card" key={title}><span className="service-index">0{i+1}</span><h3>{title}</h3><p>{text}</p><Link href="/request">Tell us about this <ArrowRight size={17}/></Link></article>)}</div></div></section>
<section className="section band" aria-labelledby="steps-heading"><div className="container"><p className="eyebrow green">NO SURPRISES</p><h2 id="steps-heading">We talk first. Then we schedule.</h2><div className="steps"><div><span>1</span><h3>Tell us what needs doing.</h3><p>Give us the basics by form, phone, or text. No account is needed.</p></div><div><span>2</span><h3>We go over the work.</h3><p>We confirm whether it fits, what is included, and the cost before setting a time.</p></div><div><span>3</span><h3>We come by when agreed.</h3><p>You know the plan before work begins. A request is not a booking.</p></div></div></div></section>
<section className="rate"><div className="container rate-inner"><div><p className="eyebrow">🇺🇸 COMMUNITY RATE</p><h2>Built with our neighbors in mind.</h2><p>Our Community Rate is for <strong>seniors 70+, veterans, single moms, and people with disabilities</strong>. It is <strong>$45 an hour</strong>, with a two-hour minimum. No proof, paperwork, income details, or diagnosis is required.</p><p>We also take requests from other neighbors when the work fits. This rate is here for the neighbors who may need more room in the budget.</p></div><Link className="button button-light" href="/pricing">See the rates <ArrowRight size={18}/></Link></div></section>
<RequestForm />
</>;}
