"use client";
import {useEffect,useRef,useState} from 'react';
import {sessionFetch} from '../../../lib/session-fetch';
import {taxProfileSchema,taxRuleSchema,estimatedInstallments,ratePpm,taxSources,illinoisEstimate2026,type TaxProfile,type TaxRule} from '../../../lib/taxes';
import {invoiceChargeCents} from '../../../lib/invoice-charge';
const money=(c:number)=>(c/100).toLocaleString('en-US',{style:'currency',currency:'USD'});
type RecordRow={id:string;recordType:'deadline'|'payment'|'reversal';recordedAt:string;data:{year:number;kind:string;label:string;period:string;date:string;amountCents:number;reference?:string;sourceUrl:string;paymentUrl:string;recordId?:string;reason?:string;deadlineId?:string}};
type Data={profile:{version:number;data:TaxProfile}|null;records:RecordRow[];invoices:{id:string;number:number;subtotalCents:number;taxCents:number;totalCents:number;paidCents:number}[];today:string;canEdit:boolean};
type Due={id:string;kind:string;label:string;period:string;dueDate:string;amountCents:number;sourceUrl:string;paymentUrl:string};
export default function Taxes(){
 const [org,setOrg]=useState(''),[year,setYear]=useState(2026),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[payment,setPayment]=useState<Due|null>(null);
 const [rules,setRules]=useState<TaxRule[]>([]);const loadGeneration=useRef(0),mounted=useRef(true),sending=useRef(false),retry=useRef<{value:string;key:string}|null>(null);
 async function load(organization=org,selectedYear=year){const generation=++loadGeneration.current;const r=await sessionFetch('/api/taxes?'+new URLSearchParams({organization,year:String(selectedYear)}));const d=await r.json();if(!r.ok)throw Error(d.error);if(mounted.current&&generation===loadGeneration.current){setData(d);setRules(d.profile?.data.rules||[]);}}
 useEffect(()=>{mounted.current=true;const organization=new URLSearchParams(location.search).get('organization')||'';setOrg(organization);void load(organization,year).catch(()=>setError('Tax records could not be loaded. Sign in and reopen Taxes from Money.'));return()=>{mounted.current=false};},[year]);
 async function save(action:string,value:unknown){if(sending.current)return false;sending.current=true;setBusy(true);setError('');setNotice('');
 try{const body={organization:org,version:data?.profile?.version||0,action,data:value};const fingerprint=JSON.stringify(body);if(retry.current?.value!==fingerprint)retry.current={value:fingerprint,key:crypto.randomUUID()};const r=await sessionFetch('/api/taxes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,key:retry.current.key})});const d=await r.json();if(!r.ok)throw Error(d.error);retry.current=null;await load();if(mounted.current)setNotice(action==='payment'?'Confirmed tax payment recorded. This does not send money to a tax authority.':'Tax record saved.');return true;}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'The tax record was not saved.');return false;}finally{sending.current=false;if(mounted.current)setBusy(false);}}
 const profile=data?.profile?.data;
 const reversed=new Set(data?.records.filter(r=>r.recordType==='reversal').map(r=>r.data.recordId));
 const active=data?.records.filter(r=>!reversed.has(r.id)&&r.recordType!=='reversal')||[];
 const planned=profile?.year===year?estimatedInstallments(profile):[];
 const due:Due[]=[...planned,...active.filter(r=>r.recordType==='deadline').map(r=>({id:r.id,kind:r.data.kind,label:r.data.label,period:r.data.period,dueDate:r.data.date,amountCents:r.data.amountCents,sourceUrl:r.data.sourceUrl,paymentUrl:r.data.paymentUrl}))].sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
 const paidFor=(id:string)=>active.filter(r=>r.recordType==='payment'&&r.data.deadlineId===id).reduce((s,r)=>s+r.data.amountCents,0);
 function amount(f:FormData,key:string,optional=false){const raw=String(f.get(key)||'');if(optional&&!raw)return null;const n=invoiceChargeCents(raw);if(n===null)throw Error('Enter dollars with up to two decimal places.');return n;}
 const submitted=(work:()=>void|Promise<void>)=>{setError('');try{const r=work();if(r instanceof Promise)void r.catch(e=>setError(e instanceof Error?e.message:'Check the tax entry.'));}catch(e){setError(e instanceof Error?e.message:'Check the tax entry.');}};
 return <main id="main" className="shell invoice-document"><a href="/owner">Back to workspace</a><div className="section-heading"><div><p className="eyebrow">Money</p><h1>Taxes</h1></div><label>Tax year<select value={year} disabled={busy} onChange={e=>{setData(null);setYear(Number(e.target.value));}}>{[2026,2027,2028].map(y=><option key={y}>{y}</option>)}</select></label></div>
 <p>Customer sales tax, owner income estimates and confirmed tax payments in one place. Your reviewed rules determine the amounts; the CRM keeps the records.</p>
 {error&&<p role="alert" className="note">{error}</p>}{notice&&<p role="status" className="note">{notice}</p>}{!data&&!error&&<p role="status">Loading tax records…</p>}
 {data&&<>
 <section className="card"><h2>{year} overview</h2><div className="metric-grid"><p>Sales tax invoiced<br/><strong>{money(data.invoices.reduce((s,i)=>s+i.taxCents,0))}</strong></p><p>Sales / use tax payments recorded<br/><strong>{money(active.filter(r=>r.recordType==='payment'&&['sales_tax','use_tax'].includes(r.data.kind)).reduce((s,r)=>s+r.data.amountCents,0))}</strong></p><p>Owner estimated tax payments recorded<br/><strong>{money(active.filter(r=>r.recordType==='payment'&&['federal_estimated','state_income'].includes(r.data.kind)).reduce((s,r)=>s+r.data.amountCents,0))}</strong></p></div><p className="note">Sales tax invoiced is an accrual total, not a filed return or proof of collection. Tax-payment totals use the selected tax year. Income tax and sales tax are separate obligations.</p>
 {!profile&&<p className="note">Add reviewed tax setup before applying new sales-tax rules. Existing invoices keep their issued amounts.</p>}
 {profile&&<p>Setup version {data.profile?.version} · {profile.state} · reviewed {profile.reviewedOn} · {profile.year}. {profile.entity==='individual_calendar'?'Individual, calendar-year worksheet.':'Entity-specific dates and amounts require reviewed entries.'}</p>}
 {profile?.year!==year&&profile&&<p className="note">The current setup is for {profile.year}. Review and save setup for {year}; prior tax years are never carried forward automatically.</p>}
 <a href={'/api/taxes?'+new URLSearchParams({organization:org,year:String(year),format:'csv'})}>Export tax records (.csv)</a><p>Accountant export with exact cents, jurisdiction components, sources, payments and reversals. Match these columns to the receiving software. QuickBooks invoice CSV import has restrictions when sales tax is enabled; this file does not claim universal direct import.</p></section>
 <section className="card"><h2>Payment calendar</h2><p>2026 federal individual and Illinois individual dates are verified. State sales-tax frequency, local taxes, other entities and 2027 dates need the authority’s assigned deadlines. Illinois individual installments use the form’s whole-dollar rounding; their total can differ slightly from the net annual estimate. A payment link opens the authority; nothing is paid automatically.</p>
 {!due.length&&<p>No reviewed payment deadlines for this year.</p>}
 {due.map(d=>{const paid=paidFor(d.id),remaining=Math.max(0,d.amountCents-paid);return <article key={d.id} className="card"><div className="section-heading"><div><h3>{d.label}</h3><p>{d.period} · due {d.dueDate}</p></div><strong>{remaining===0?'Recorded as paid':d.dueDate<data.today?'Due date passed':d.dueDate===data.today?'Due today':'Upcoming'}</strong></div><p>Planned {money(d.amountCents)} · recorded payments {money(paid)} · remaining {money(remaining)}</p>{paid>d.amountCents&&<p>Payments exceed this planned amount. Review its allocation.</p>}<div className="actions"><a href={d.sourceUrl} target="_blank" rel="noopener noreferrer">Filing rules</a>{d.paymentUrl&&<a href={d.paymentUrl} target="_blank" rel="noopener noreferrer">Official payment site</a>}{data.canEdit&&remaining>0&&<button disabled={busy} onClick={()=>setPayment(d)}>Record a tax payment</button>}{data.canEdit&&!planned.some(p=>p.id===d.id)&&<button className="secondary" disabled={busy} onClick={()=>{const reason=prompt('Reason for reversing this deadline');if(reason)void save('reversal',{year,recordId:d.id,reason});}}>Reverse deadline</button>}</div></article>})}
 </section>
 {data.canEdit&&<details className="card" open={Boolean(payment)}><summary>{payment?'Record payment for '+payment.period:'Add a filing deadline or confirmed tax payment'}</summary><form key={payment?.id||'manual'} onSubmit={e=>{e.preventDefault();const form=e.currentTarget;submitted(async()=>{const f=new FormData(form),action=String(f.get('action'));const value={year,kind:String(f.get('kind')),label:String(f.get('label')),period:String(f.get('period')),date:String(f.get('date')),amountCents:amount(f,'amount'),sourceUrl:String(f.get('source')),paymentUrl:String(f.get('paymentUrl')),reference:String(f.get('reference')),deadlineId:payment?.id||'',reviewed:true};if(await save(action,value)){form.reset();setPayment(null);}});}}><fieldset disabled={busy}><legend>Tax entry</legend><label>Entry type<select name="action" defaultValue={payment?'payment':'deadline'}><option value="deadline">Filing / payment deadline</option><option value="payment">Confirmed payment already made</option></select></label><label>Tax category<select name="kind" defaultValue={payment?.kind||'sales_tax'}><option value="federal_estimated">Federal estimated (income + applicable self-employment)</option><option value="state_income">State income</option><option value="sales_tax">Sales tax</option><option value="use_tax">Use tax</option><option value="other">Other reviewed tax</option></select></label><label>Authority / jurisdiction<input required minLength={2} maxLength={500} name="label" defaultValue={payment?.label||''}/></label><label>Reporting period<input required minLength={2} maxLength={500} name="period" defaultValue={payment?.period||''}/></label><label>Date (deadline or actual payment)<input type="date" required name="date" defaultValue={payment?data.today:''}/></label><label>Amount ($)<input required inputMode="decimal" name="amount" defaultValue={payment?(Math.max(0,payment.amountCents-paidFor(payment.id))/100).toFixed(2):''}/></label><label>Confirmation / receipt reference (required for payments)<input maxLength={500} name="reference"/></label><label>Official rule / form URL<input type="url" required name="source" defaultValue={payment?.sourceUrl||''}/></label><label>Official payment URL<input type="url" required name="paymentUrl" defaultValue={payment?.paymentUrl||''}/></label><label><input type="checkbox" required/>I verified the deadline or actual payment with the authority. This entry does not submit a return or send money.</label><button>Save tax entry</button>{payment&&<button type="button" className="secondary" onClick={()=>setPayment(null)}>Cancel</button>}</fieldset></form></details>}
 <details className="card"><summary>Tax payment history and corrections</summary>{!data.records.length&&<p>No recorded tax entries.</p>}{data.records.map(r=><article key={r.id}><h3>{r.data.label||'Correction'} · {r.recordType}</h3><p>{r.data.date||r.recordedAt} · {r.data.period} · {r.data.amountCents!==undefined?money(r.data.amountCents):r.data.reason} {reversed.has(r.id)?'· Reversed':''}</p>{r.data.reference&&<p>Receipt: {r.data.reference}</p>}{r.data.recordId&&<p>Reverses record {r.data.recordId}</p>}{data.canEdit&&r.recordType==='payment'&&!reversed.has(r.id)&&<button className="secondary" disabled={busy} onClick={()=>{const reason=prompt('Reason for reversing this payment record (no refund is sent)');if(reason)void save('reversal',{year,recordId:r.id,reason});}}>Correct by reversal</button>}</article>)}</details>
 {data.canEdit&&<details className="card"><summary>Tax setup and reviewed sales-tax rules</summary><p>Use your completed 1040-ES and state worksheet or your accountant’s amounts. The federal amount must include applicable self-employment and other taxes, credits and withholding. Blank means not reviewed; zero means a reviewed zero. Do not enter gross revenue as taxable income.</p>
 <form key={String(data.profile?.version||0)+':'+year} onSubmit={e=>{e.preventDefault();submitted(async()=>{const f=new FormData(e.currentTarget);const p=taxProfileSchema.parse({year,state:String(f.get('state')).toUpperCase(),entity:String(f.get('entity')),federalAnnualPaymentCents:amount(f,'federal',true),stateAnnualPaymentCents:amount(f,'statePayment',true),federalSource:String(f.get('federalSource')),stateSource:String(f.get('stateSource')),reviewedOn:String(f.get('reviewedOn')),reviewNote:String(f.get('reviewNote')),rules});await save('profile',p);});}}><fieldset disabled={busy}><legend>Reviewed setup for {year}</legend><label>Operating state (two-letter code)<input name="state" required pattern="[A-Za-z]{2}" maxLength={2} defaultValue={profile?.state||''}/></label><label>Filing setup<select name="entity" defaultValue={profile?.entity||'other'}><option value="other">Entity-specific / accountant review</option><option value="individual_calendar">Individual calendar year (1040-ES)</option></select></label><label>Federal annual estimated payments from completed worksheet ($)<input name="federal" inputMode="decimal" defaultValue={profile?.year===year&&profile.federalAnnualPaymentCents!==null?(profile.federalAnnualPaymentCents/100).toFixed(2):''}/></label><label>State annual estimated payments from completed worksheet ($)<input name="statePayment" inputMode="decimal" defaultValue={profile?.year===year&&profile.stateAnnualPaymentCents!==null?(profile.stateAnnualPaymentCents/100).toFixed(2):''}/></label><label>Federal source / form<input name="federalSource" type="url" required defaultValue={profile?.federalSource||taxSources.federal}/></label><label>State source / form<input name="stateSource" type="url" required defaultValue={profile?.stateSource||''}/></label><label>Reviewed on<input name="reviewedOn" type="date" required max={data.today} defaultValue={data.today}/></label><label>Review evidence (registration, accountant or official worksheet)<textarea name="reviewNote" required minLength={2} maxLength={500} defaultValue={profile?.reviewNote||''}/></label><h3>Sales-tax rules to publish</h3>{rules.map(r=><article key={r.id}><strong>{r.label}</strong><p>{r.city}, {r.county}, {r.state} · {r.effectiveFrom} through {r.effectiveTo}</p><p>{r.scope}</p><p>{r.components.map(c=>`${c.label}: ${(c.ratePpm/10000).toFixed(4).replace(/0+$/,'').replace(/\.$/,'')}%`).join(' · ')}</p><button type="button" className="secondary" onClick={()=>setRules(old=>old.filter(x=>x.id!==r.id))}>Remove from next setup version</button></article>)}<label><input type="checkbox" required/>I reviewed the rules, service scope, sourcing, rounding method and worksheet amounts. Any new rule must be reviewed for each invoice’s actual address and work.</label><button>Publish reviewed tax setup</button></fieldset></form>
 <details><summary>Add a reviewed rule to this setup</summary><p>Applies to the entire labor-only invoice. Materials, mixed taxable/exempt services and alternative rounding methods need a separate reviewed calculation; do not use this rule for those invoices. A zero-rate rule requires a documented exemption or non-taxable labor decision. County / district boundaries must be verified for the exact address, not guessed from city or ZIP.</p><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;submitted(()=>{const f=new FormData(form);const components=(['state','county','city','district'] as const).flatMap(kind=>{const raw=String(f.get(kind+'Rate')||'');if(!raw)return [];const rate=ratePpm(raw);if(rate===null)throw Error('Use a percentage with up to four decimal places (for example 6.25).');return [{kind,label:String(f.get(kind+'Label')||kind+' tax'),ratePpm:rate}];});const rule=taxRuleSchema.parse({id:crypto.randomUUID(),label:String(f.get('label')),state:String(f.get('state')).toUpperCase(),county:String(f.get('county')),city:String(f.get('city')),jurisdictionEvidence:String(f.get('evidence')),scope:String(f.get('scope')),effectiveFrom:String(f.get('from')),effectiveTo:String(f.get('to')),reviewedOn:data.today,sourceUrl:String(f.get('source')),components,rounding:'component_half_up',reviewed:true});setRules(old=>[...old,rule]);setNotice('Rule added to the form. Publish reviewed setup to save it.');form.reset();});}}><fieldset disabled={busy}><legend>Sales-tax rule</legend><label>Rule name<input name="label" required minLength={2} maxLength={500}/></label><label>State<input name="state" required pattern="[A-Za-z]{2}" defaultValue={profile?.state||''}/></label><label>County<input name="county" required minLength={2}/></label><label>City / municipality<input name="city" required minLength={2}/></label><label>Service scope and tax treatment<textarea name="scope" required minLength={2} maxLength={500}/></label><label>Address sourcing / boundary verification<textarea name="evidence" required minLength={2} maxLength={500}/></label><label>Effective from<input name="from" type="date" required/></label><label>Effective through<input name="to" type="date" required/></label><label>Official tax rule / rate source<input name="source" type="url" required/></label>{(['state','county','city','district'] as const).map(kind=><fieldset key={kind}><legend>{kind.charAt(0).toUpperCase()+kind.slice(1)} component</legend><label>Authority name<input name={kind+'Label'} defaultValue={kind+' tax'}/></label><label>Rate (%) — blank omits this component<input name={kind+'Rate'} inputMode="decimal" placeholder="6.25"/></label></fieldset>)}<label><input type="checkbox" required/>I verified this rule with its authority and confirmed component-by-component cent rounding.</label><button>Add rule to setup form</button></fieldset></form></details></details>}
 <details className="card"><summary>Illinois individual estimate helper (2026)</summary><p>Uses 4.95% of net Illinois income after exemptions, plus supplied surcharges, minus withholding and credits. The 2026 worksheet requires estimated payments when the result exceeds $1,000. This helper does not handle entity returns, special exceptions or annualized installments.</p><form onSubmit={e=>{e.preventDefault();submitted(()=>{const f=new FormData(e.currentTarget),r=illinoisEstimate2026(amount(f,'income')!,amount(f,'surcharges')!,amount(f,'credits')!);setNotice(`Illinois 2026 projected liability ${money(r.liabilityCents)}; net after withholding and credits ${money(r.netTaxCents)}; worksheet annual estimated-payment amount ${money(r.annualPaymentCents)}. Review the official worksheet before publishing setup.`);});}}><label>Net Illinois taxable income after exemptions ($)<input name="income" required inputMode="decimal"/></label><label>Applicable surcharges ($)<input name="surcharges" required inputMode="decimal" defaultValue="0"/></label><label>Withholding and all applicable credits ($)<input name="credits" required inputMode="decimal" defaultValue="0"/></label><button disabled={busy}>Calculate worksheet estimate</button></form></details>
 <section className="card"><h2>Verified sources and payment sites</h2><ul><li><a href={taxSources.federal}>IRS 2026 Form 1040-ES — income, self-employment and other applicable taxes</a></li><li><a href={taxSources.federalPayment}>IRS Direct Pay</a></li><li><a href={taxSources.selfEmployment}>IRS self-employment tax rules</a></li><li><a href={taxSources.illinois}>Illinois 2026 IL-1040-ES worksheet and dates</a></li><li><a href={taxSources.illinoisPayment}>MyTax Illinois — filing and payments</a></li><li><a href={taxSources.illinoisSales}>Illinois service occupation tax — labor and materials</a></li><li><a href={taxSources.illinoisRates}>Illinois official tax rates</a></li><li><a href={taxSources.illinoisFiling}>Illinois ST-1 filing instructions</a></li><li><a href={taxSources.quickbooks}>QuickBooks invoice CSV import limitations</a></li></ul><p>Tax authorities administer state, county, city and special-district taxes; they are not necessarily four separate payments. 2027 rules remain review-required until verified. The CRM does not file returns, debit bank accounts or certify a payment reached an authority.</p></section>
 </>}
 </main>;
}
